package internal

import "github.com/KhaledSaeed004/goqr/ecc"

var QRTable = map[int]map[ecc.ECLevel]QRSpec{
	1: {
		ecc.L: {ECCodewordsPerBlock: 7, Groups: []BlockGroup{{NumBlocks: 1, DataCodewords: 19}}},
		ecc.M: {ECCodewordsPerBlock: 10, Groups: []BlockGroup{{NumBlocks: 1, DataCodewords: 16}}},
		ecc.Q: {ECCodewordsPerBlock: 13, Groups: []BlockGroup{{NumBlocks: 1, DataCodewords: 13}}},
		ecc.H: {ECCodewordsPerBlock: 17, Groups: []BlockGroup{{NumBlocks: 1, DataCodewords: 9}}},
	},
	2: {
		ecc.L: {ECCodewordsPerBlock: 10, Groups: []BlockGroup{{NumBlocks: 1, DataCodewords: 34}}},
		ecc.M: {ECCodewordsPerBlock: 16, Groups: []BlockGroup{{NumBlocks: 1, DataCodewords: 28}}},
		ecc.Q: {ECCodewordsPerBlock: 22, Groups: []BlockGroup{{NumBlocks: 1, DataCodewords: 22}}},
		ecc.H: {ECCodewordsPerBlock: 28, Groups: []BlockGroup{{NumBlocks: 1, DataCodewords: 16}}},
	},
	3: {
		ecc.L: {ECCodewordsPerBlock: 15, Groups: []BlockGroup{{NumBlocks: 1, DataCodewords: 55}}},
		ecc.M: {ECCodewordsPerBlock: 26, Groups: []BlockGroup{{NumBlocks: 1, DataCodewords: 44}}},
		ecc.Q: {ECCodewordsPerBlock: 18, Groups: []BlockGroup{{NumBlocks: 2, DataCodewords: 17}}},
		ecc.H: {ECCodewordsPerBlock: 22, Groups: []BlockGroup{{NumBlocks: 2, DataCodewords: 13}}},
	},
	4: {
		ecc.L: {ECCodewordsPerBlock: 20, Groups: []BlockGroup{{NumBlocks: 1, DataCodewords: 80}}},
		ecc.M: {ECCodewordsPerBlock: 18, Groups: []BlockGroup{{NumBlocks: 2, DataCodewords: 32}}},
		ecc.Q: {ECCodewordsPerBlock: 26, Groups: []BlockGroup{{NumBlocks: 2, DataCodewords: 24}}},
		ecc.H: {ECCodewordsPerBlock: 16, Groups: []BlockGroup{{NumBlocks: 4, DataCodewords: 9}}},
	},
	5: {
		ecc.L: {ECCodewordsPerBlock: 26, Groups: []BlockGroup{{NumBlocks: 1, DataCodewords: 108}}},
		ecc.M: {ECCodewordsPerBlock: 24, Groups: []BlockGroup{{NumBlocks: 2, DataCodewords: 43}}},
		ecc.Q: {ECCodewordsPerBlock: 18, Groups: []BlockGroup{{NumBlocks: 2, DataCodewords: 15}, {NumBlocks: 2, DataCodewords: 16}}},
		ecc.H: {ECCodewordsPerBlock: 22, Groups: []BlockGroup{{NumBlocks: 2, DataCodewords: 11}, {NumBlocks: 2, DataCodewords: 12}}},
	},
	6: {
		ecc.L: {ECCodewordsPerBlock: 18, Groups: []BlockGroup{{NumBlocks: 2, DataCodewords: 68}}},
		ecc.M: {ECCodewordsPerBlock: 16, Groups: []BlockGroup{{NumBlocks: 4, DataCodewords: 27}}},
		ecc.Q: {ECCodewordsPerBlock: 24, Groups: []BlockGroup{{NumBlocks: 4, DataCodewords: 19}}},
		ecc.H: {ECCodewordsPerBlock: 28, Groups: []BlockGroup{{NumBlocks: 4, DataCodewords: 15}}},
	},
	7: {
		ecc.L: {ECCodewordsPerBlock: 20, Groups: []BlockGroup{{NumBlocks: 2, DataCodewords: 78}}},
		ecc.M: {ECCodewordsPerBlock: 18, Groups: []BlockGroup{{NumBlocks: 4, DataCodewords: 31}}},
		ecc.Q: {ECCodewordsPerBlock: 18, Groups: []BlockGroup{{NumBlocks: 2, DataCodewords: 14}, {NumBlocks: 4, DataCodewords: 15}}},
		ecc.H: {ECCodewordsPerBlock: 26, Groups: []BlockGroup{{NumBlocks: 4, DataCodewords: 13}, {NumBlocks: 1, DataCodewords: 14}}},
	},
	8: {
		ecc.L: {ECCodewordsPerBlock: 24, Groups: []BlockGroup{{NumBlocks: 2, DataCodewords: 97}}},
		ecc.M: {ECCodewordsPerBlock: 22, Groups: []BlockGroup{{NumBlocks: 2, DataCodewords: 38}, {NumBlocks: 2, DataCodewords: 39}}},
		ecc.Q: {ECCodewordsPerBlock: 22, Groups: []BlockGroup{{NumBlocks: 4, DataCodewords: 18}, {NumBlocks: 2, DataCodewords: 19}}},
		ecc.H: {ECCodewordsPerBlock: 26, Groups: []BlockGroup{{NumBlocks: 4, DataCodewords: 14}, {NumBlocks: 2, DataCodewords: 15}}},
	},
	9: {
		ecc.L: {ECCodewordsPerBlock: 30, Groups: []BlockGroup{{NumBlocks: 2, DataCodewords: 116}}},
		ecc.M: {ECCodewordsPerBlock: 22, Groups: []BlockGroup{{NumBlocks: 3, DataCodewords: 36}, {NumBlocks: 2, DataCodewords: 37}}},
		ecc.Q: {ECCodewordsPerBlock: 20, Groups: []BlockGroup{{NumBlocks: 4, DataCodewords: 16}, {NumBlocks: 4, DataCodewords: 17}}},
		ecc.H: {ECCodewordsPerBlock: 24, Groups: []BlockGroup{{NumBlocks: 4, DataCodewords: 12}, {NumBlocks: 4, DataCodewords: 13}}},
	},
	10: {
		ecc.L: {ECCodewordsPerBlock: 18, Groups: []BlockGroup{{NumBlocks: 2, DataCodewords: 68}, {NumBlocks: 2, DataCodewords: 69}}},
		ecc.M: {ECCodewordsPerBlock: 26, Groups: []BlockGroup{{NumBlocks: 4, DataCodewords: 43}, {NumBlocks: 1, DataCodewords: 44}}},
		ecc.Q: {ECCodewordsPerBlock: 24, Groups: []BlockGroup{{NumBlocks: 6, DataCodewords: 19}, {NumBlocks: 2, DataCodewords: 20}}},
		ecc.H: {ECCodewordsPerBlock: 28, Groups: []BlockGroup{{NumBlocks: 6, DataCodewords: 15}, {NumBlocks: 2, DataCodewords: 16}}},
	},
	11: {
		ecc.L: {ECCodewordsPerBlock: 20, Groups: []BlockGroup{{NumBlocks: 4, DataCodewords: 81}}},
		ecc.M: {ECCodewordsPerBlock: 30, Groups: []BlockGroup{{NumBlocks: 1, DataCodewords: 50}, {NumBlocks: 4, DataCodewords: 51}}},
		ecc.Q: {ECCodewordsPerBlock: 28, Groups: []BlockGroup{{NumBlocks: 4, DataCodewords: 22}, {NumBlocks: 4, DataCodewords: 23}}},
		ecc.H: {ECCodewordsPerBlock: 24, Groups: []BlockGroup{{NumBlocks: 3, DataCodewords: 12}, {NumBlocks: 8, DataCodewords: 13}}},
	},
	12: {
		ecc.L: {ECCodewordsPerBlock: 24, Groups: []BlockGroup{{NumBlocks: 2, DataCodewords: 92}, {NumBlocks: 2, DataCodewords: 93}}},
		ecc.M: {ECCodewordsPerBlock: 22, Groups: []BlockGroup{{NumBlocks: 6, DataCodewords: 36}, {NumBlocks: 2, DataCodewords: 37}}},
		ecc.Q: {ECCodewordsPerBlock: 26, Groups: []BlockGroup{{NumBlocks: 4, DataCodewords: 20}, {NumBlocks: 6, DataCodewords: 21}}},
		ecc.H: {ECCodewordsPerBlock: 28, Groups: []BlockGroup{{NumBlocks: 7, DataCodewords: 14}, {NumBlocks: 4, DataCodewords: 15}}},
	},
	13: {
		ecc.L: {ECCodewordsPerBlock: 26, Groups: []BlockGroup{{NumBlocks: 4, DataCodewords: 107}}},
		ecc.M: {ECCodewordsPerBlock: 22, Groups: []BlockGroup{{NumBlocks: 8, DataCodewords: 37}, {NumBlocks: 1, DataCodewords: 38}}},
		ecc.Q: {ECCodewordsPerBlock: 24, Groups: []BlockGroup{{NumBlocks: 8, DataCodewords: 20}, {NumBlocks: 4, DataCodewords: 21}}},
		ecc.H: {ECCodewordsPerBlock: 22, Groups: []BlockGroup{{NumBlocks: 12, DataCodewords: 11}, {NumBlocks: 4, DataCodewords: 12}}},
	},
	14: {
		ecc.L: {ECCodewordsPerBlock: 30, Groups: []BlockGroup{{NumBlocks: 3, DataCodewords: 115}, {NumBlocks: 1, DataCodewords: 116}}},
		ecc.M: {ECCodewordsPerBlock: 24, Groups: []BlockGroup{{NumBlocks: 4, DataCodewords: 40}, {NumBlocks: 5, DataCodewords: 41}}},
		ecc.Q: {ECCodewordsPerBlock: 20, Groups: []BlockGroup{{NumBlocks: 11, DataCodewords: 16}, {NumBlocks: 5, DataCodewords: 17}}},
		ecc.H: {ECCodewordsPerBlock: 24, Groups: []BlockGroup{{NumBlocks: 11, DataCodewords: 12}, {NumBlocks: 5, DataCodewords: 13}}},
	},
	15: {
		ecc.L: {ECCodewordsPerBlock: 22, Groups: []BlockGroup{{NumBlocks: 5, DataCodewords: 87}, {NumBlocks: 1, DataCodewords: 88}}},
		ecc.M: {ECCodewordsPerBlock: 24, Groups: []BlockGroup{{NumBlocks: 5, DataCodewords: 41}, {NumBlocks: 5, DataCodewords: 42}}},
		ecc.Q: {ECCodewordsPerBlock: 30, Groups: []BlockGroup{{NumBlocks: 5, DataCodewords: 24}, {NumBlocks: 7, DataCodewords: 25}}},
		ecc.H: {ECCodewordsPerBlock: 24, Groups: []BlockGroup{{NumBlocks: 11, DataCodewords: 12}, {NumBlocks: 7, DataCodewords: 13}}},
	},
	16: {
		ecc.L: {ECCodewordsPerBlock: 24, Groups: []BlockGroup{{NumBlocks: 5, DataCodewords: 98}, {NumBlocks: 1, DataCodewords: 99}}},
		ecc.M: {ECCodewordsPerBlock: 28, Groups: []BlockGroup{{NumBlocks: 7, DataCodewords: 45}, {NumBlocks: 3, DataCodewords: 46}}},
		ecc.Q: {ECCodewordsPerBlock: 24, Groups: []BlockGroup{{NumBlocks: 15, DataCodewords: 19}, {NumBlocks: 2, DataCodewords: 20}}},
		ecc.H: {ECCodewordsPerBlock: 30, Groups: []BlockGroup{{NumBlocks: 3, DataCodewords: 15}, {NumBlocks: 13, DataCodewords: 16}}},
	},
	17: {
		ecc.L: {ECCodewordsPerBlock: 28, Groups: []BlockGroup{{NumBlocks: 1, DataCodewords: 107}, {NumBlocks: 5, DataCodewords: 108}}},
		ecc.M: {ECCodewordsPerBlock: 28, Groups: []BlockGroup{{NumBlocks: 10, DataCodewords: 46}, {NumBlocks: 1, DataCodewords: 47}}},
		ecc.Q: {ECCodewordsPerBlock: 28, Groups: []BlockGroup{{NumBlocks: 1, DataCodewords: 22}, {NumBlocks: 15, DataCodewords: 23}}},
		ecc.H: {ECCodewordsPerBlock: 28, Groups: []BlockGroup{{NumBlocks: 2, DataCodewords: 14}, {NumBlocks: 17, DataCodewords: 15}}},
	},
	18: {
		ecc.L: {ECCodewordsPerBlock: 30, Groups: []BlockGroup{{NumBlocks: 5, DataCodewords: 120}, {NumBlocks: 1, DataCodewords: 121}}},
		ecc.M: {ECCodewordsPerBlock: 26, Groups: []BlockGroup{{NumBlocks: 9, DataCodewords: 43}, {NumBlocks: 4, DataCodewords: 44}}},
		ecc.Q: {ECCodewordsPerBlock: 28, Groups: []BlockGroup{{NumBlocks: 17, DataCodewords: 22}, {NumBlocks: 1, DataCodewords: 23}}},
		ecc.H: {ECCodewordsPerBlock: 28, Groups: []BlockGroup{{NumBlocks: 2, DataCodewords: 14}, {NumBlocks: 19, DataCodewords: 15}}},
	},
	19: {
		ecc.L: {ECCodewordsPerBlock: 28, Groups: []BlockGroup{{NumBlocks: 3, DataCodewords: 113}, {NumBlocks: 4, DataCodewords: 114}}},
		ecc.M: {ECCodewordsPerBlock: 26, Groups: []BlockGroup{{NumBlocks: 3, DataCodewords: 44}, {NumBlocks: 11, DataCodewords: 45}}},
		ecc.Q: {ECCodewordsPerBlock: 26, Groups: []BlockGroup{{NumBlocks: 17, DataCodewords: 21}, {NumBlocks: 4, DataCodewords: 22}}},
		ecc.H: {ECCodewordsPerBlock: 26, Groups: []BlockGroup{{NumBlocks: 9, DataCodewords: 13}, {NumBlocks: 16, DataCodewords: 14}}},
	},
	20: {
		ecc.L: {ECCodewordsPerBlock: 28, Groups: []BlockGroup{{NumBlocks: 3, DataCodewords: 107}, {NumBlocks: 5, DataCodewords: 108}}},
		ecc.M: {ECCodewordsPerBlock: 26, Groups: []BlockGroup{{NumBlocks: 3, DataCodewords: 41}, {NumBlocks: 13, DataCodewords: 42}}},
		ecc.Q: {ECCodewordsPerBlock: 30, Groups: []BlockGroup{{NumBlocks: 15, DataCodewords: 24}, {NumBlocks: 5, DataCodewords: 25}}},
		ecc.H: {ECCodewordsPerBlock: 28, Groups: []BlockGroup{{NumBlocks: 15, DataCodewords: 15}, {NumBlocks: 10, DataCodewords: 16}}},
	},
	21: {
		ecc.L: {ECCodewordsPerBlock: 28, Groups: []BlockGroup{{NumBlocks: 4, DataCodewords: 116}, {NumBlocks: 4, DataCodewords: 117}}},
		ecc.M: {ECCodewordsPerBlock: 26, Groups: []BlockGroup{{NumBlocks: 17, DataCodewords: 42}}},
		ecc.Q: {ECCodewordsPerBlock: 28, Groups: []BlockGroup{{NumBlocks: 17, DataCodewords: 22}, {NumBlocks: 6, DataCodewords: 23}}},
		ecc.H: {ECCodewordsPerBlock: 30, Groups: []BlockGroup{{NumBlocks: 19, DataCodewords: 16}, {NumBlocks: 6, DataCodewords: 17}}},
	},
	22: {
		ecc.L: {ECCodewordsPerBlock: 28, Groups: []BlockGroup{{NumBlocks: 2, DataCodewords: 111}, {NumBlocks: 7, DataCodewords: 112}}},
		ecc.M: {ECCodewordsPerBlock: 28, Groups: []BlockGroup{{NumBlocks: 17, DataCodewords: 46}}},
		ecc.Q: {ECCodewordsPerBlock: 30, Groups: []BlockGroup{{NumBlocks: 7, DataCodewords: 24}, {NumBlocks: 16, DataCodewords: 25}}},
		ecc.H: {ECCodewordsPerBlock: 24, Groups: []BlockGroup{{NumBlocks: 34, DataCodewords: 13}}},
	},
	23: {
		ecc.L: {ECCodewordsPerBlock: 30, Groups: []BlockGroup{{NumBlocks: 4, DataCodewords: 121}, {NumBlocks: 5, DataCodewords: 122}}},
		ecc.M: {ECCodewordsPerBlock: 28, Groups: []BlockGroup{{NumBlocks: 4, DataCodewords: 47}, {NumBlocks: 14, DataCodewords: 48}}},
		ecc.Q: {ECCodewordsPerBlock: 30, Groups: []BlockGroup{{NumBlocks: 11, DataCodewords: 24}, {NumBlocks: 14, DataCodewords: 25}}},
		ecc.H: {ECCodewordsPerBlock: 30, Groups: []BlockGroup{{NumBlocks: 16, DataCodewords: 15}, {NumBlocks: 14, DataCodewords: 16}}},
	},
	24: {
		ecc.L: {ECCodewordsPerBlock: 30, Groups: []BlockGroup{{NumBlocks: 6, DataCodewords: 117}, {NumBlocks: 4, DataCodewords: 118}}},
		ecc.M: {ECCodewordsPerBlock: 28, Groups: []BlockGroup{{NumBlocks: 6, DataCodewords: 45}, {NumBlocks: 14, DataCodewords: 46}}},
		ecc.Q: {ECCodewordsPerBlock: 30, Groups: []BlockGroup{{NumBlocks: 11, DataCodewords: 24}, {NumBlocks: 16, DataCodewords: 25}}},
		ecc.H: {ECCodewordsPerBlock: 30, Groups: []BlockGroup{{NumBlocks: 30, DataCodewords: 16}, {NumBlocks: 2, DataCodewords: 17}}},
	},
	25: {
		ecc.L: {ECCodewordsPerBlock: 26, Groups: []BlockGroup{{NumBlocks: 8, DataCodewords: 106}, {NumBlocks: 4, DataCodewords: 107}}},
		ecc.M: {ECCodewordsPerBlock: 28, Groups: []BlockGroup{{NumBlocks: 8, DataCodewords: 47}, {NumBlocks: 13, DataCodewords: 48}}},
		ecc.Q: {ECCodewordsPerBlock: 30, Groups: []BlockGroup{{NumBlocks: 7, DataCodewords: 24}, {NumBlocks: 22, DataCodewords: 25}}},
		ecc.H: {ECCodewordsPerBlock: 30, Groups: []BlockGroup{{NumBlocks: 22, DataCodewords: 15}, {NumBlocks: 13, DataCodewords: 16}}},
	},
	26: {
		ecc.L: {ECCodewordsPerBlock: 28, Groups: []BlockGroup{{NumBlocks: 10, DataCodewords: 114}, {NumBlocks: 2, DataCodewords: 115}}},
		ecc.M: {ECCodewordsPerBlock: 28, Groups: []BlockGroup{{NumBlocks: 19, DataCodewords: 46}, {NumBlocks: 4, DataCodewords: 47}}},
		ecc.Q: {ECCodewordsPerBlock: 28, Groups: []BlockGroup{{NumBlocks: 28, DataCodewords: 22}, {NumBlocks: 6, DataCodewords: 23}}},
		ecc.H: {ECCodewordsPerBlock: 30, Groups: []BlockGroup{{NumBlocks: 33, DataCodewords: 16}, {NumBlocks: 4, DataCodewords: 17}}},
	},
	27: {
		ecc.L: {ECCodewordsPerBlock: 30, Groups: []BlockGroup{{NumBlocks: 8, DataCodewords: 122}, {NumBlocks: 4, DataCodewords: 123}}},
		ecc.M: {ECCodewordsPerBlock: 28, Groups: []BlockGroup{{NumBlocks: 22, DataCodewords: 45}, {NumBlocks: 3, DataCodewords: 46}}},
		ecc.Q: {ECCodewordsPerBlock: 30, Groups: []BlockGroup{{NumBlocks: 8, DataCodewords: 23}, {NumBlocks: 26, DataCodewords: 24}}},
		ecc.H: {ECCodewordsPerBlock: 30, Groups: []BlockGroup{{NumBlocks: 12, DataCodewords: 15}, {NumBlocks: 28, DataCodewords: 16}}},
	},
	28: {
		ecc.L: {ECCodewordsPerBlock: 30, Groups: []BlockGroup{{NumBlocks: 3, DataCodewords: 117}, {NumBlocks: 10, DataCodewords: 118}}},
		ecc.M: {ECCodewordsPerBlock: 28, Groups: []BlockGroup{{NumBlocks: 3, DataCodewords: 45}, {NumBlocks: 23, DataCodewords: 46}}},
		ecc.Q: {ECCodewordsPerBlock: 30, Groups: []BlockGroup{{NumBlocks: 4, DataCodewords: 24}, {NumBlocks: 31, DataCodewords: 25}}},
		ecc.H: {ECCodewordsPerBlock: 30, Groups: []BlockGroup{{NumBlocks: 11, DataCodewords: 15}, {NumBlocks: 31, DataCodewords: 16}}},
	},
	29: {
		ecc.L: {ECCodewordsPerBlock: 30, Groups: []BlockGroup{{NumBlocks: 7, DataCodewords: 116}, {NumBlocks: 7, DataCodewords: 117}}},
		ecc.M: {ECCodewordsPerBlock: 28, Groups: []BlockGroup{{NumBlocks: 21, DataCodewords: 45}, {NumBlocks: 7, DataCodewords: 46}}},
		ecc.Q: {ECCodewordsPerBlock: 30, Groups: []BlockGroup{{NumBlocks: 1, DataCodewords: 23}, {NumBlocks: 37, DataCodewords: 24}}},
		ecc.H: {ECCodewordsPerBlock: 30, Groups: []BlockGroup{{NumBlocks: 19, DataCodewords: 15}, {NumBlocks: 26, DataCodewords: 16}}},
	},
	30: {
		ecc.L: {ECCodewordsPerBlock: 30, Groups: []BlockGroup{{NumBlocks: 5, DataCodewords: 115}, {NumBlocks: 10, DataCodewords: 116}}},
		ecc.M: {ECCodewordsPerBlock: 28, Groups: []BlockGroup{{NumBlocks: 19, DataCodewords: 47}, {NumBlocks: 10, DataCodewords: 48}}},
		ecc.Q: {ECCodewordsPerBlock: 30, Groups: []BlockGroup{{NumBlocks: 15, DataCodewords: 24}, {NumBlocks: 25, DataCodewords: 25}}},
		ecc.H: {ECCodewordsPerBlock: 30, Groups: []BlockGroup{{NumBlocks: 23, DataCodewords: 15}, {NumBlocks: 25, DataCodewords: 16}}},
	},
	31: {
		ecc.L: {ECCodewordsPerBlock: 30, Groups: []BlockGroup{{NumBlocks: 13, DataCodewords: 115}, {NumBlocks: 3, DataCodewords: 116}}},
		ecc.M: {ECCodewordsPerBlock: 28, Groups: []BlockGroup{{NumBlocks: 2, DataCodewords: 46}, {NumBlocks: 29, DataCodewords: 47}}},
		ecc.Q: {ECCodewordsPerBlock: 30, Groups: []BlockGroup{{NumBlocks: 42, DataCodewords: 24}, {NumBlocks: 1, DataCodewords: 25}}},
		ecc.H: {ECCodewordsPerBlock: 30, Groups: []BlockGroup{{NumBlocks: 23, DataCodewords: 15}, {NumBlocks: 28, DataCodewords: 16}}},
	},
	32: {
		ecc.L: {ECCodewordsPerBlock: 30, Groups: []BlockGroup{{NumBlocks: 17, DataCodewords: 115}}},
		ecc.M: {ECCodewordsPerBlock: 28, Groups: []BlockGroup{{NumBlocks: 10, DataCodewords: 46}, {NumBlocks: 23, DataCodewords: 47}}},
		ecc.Q: {ECCodewordsPerBlock: 30, Groups: []BlockGroup{{NumBlocks: 10, DataCodewords: 24}, {NumBlocks: 35, DataCodewords: 25}}},
		ecc.H: {ECCodewordsPerBlock: 30, Groups: []BlockGroup{{NumBlocks: 19, DataCodewords: 15}, {NumBlocks: 35, DataCodewords: 16}}},
	},
	33: {
		ecc.L: {ECCodewordsPerBlock: 30, Groups: []BlockGroup{{NumBlocks: 17, DataCodewords: 115}, {NumBlocks: 1, DataCodewords: 116}}},
		ecc.M: {ECCodewordsPerBlock: 28, Groups: []BlockGroup{{NumBlocks: 14, DataCodewords: 46}, {NumBlocks: 21, DataCodewords: 47}}},
		ecc.Q: {ECCodewordsPerBlock: 30, Groups: []BlockGroup{{NumBlocks: 29, DataCodewords: 24}, {NumBlocks: 19, DataCodewords: 25}}},
		ecc.H: {ECCodewordsPerBlock: 30, Groups: []BlockGroup{{NumBlocks: 11, DataCodewords: 15}, {NumBlocks: 46, DataCodewords: 16}}},
	},
	34: {
		ecc.L: {ECCodewordsPerBlock: 30, Groups: []BlockGroup{{NumBlocks: 13, DataCodewords: 115}, {NumBlocks: 6, DataCodewords: 116}}},
		ecc.M: {ECCodewordsPerBlock: 28, Groups: []BlockGroup{{NumBlocks: 14, DataCodewords: 46}, {NumBlocks: 23, DataCodewords: 47}}},
		ecc.Q: {ECCodewordsPerBlock: 30, Groups: []BlockGroup{{NumBlocks: 44, DataCodewords: 24}, {NumBlocks: 7, DataCodewords: 25}}},
		ecc.H: {ECCodewordsPerBlock: 30, Groups: []BlockGroup{{NumBlocks: 59, DataCodewords: 16}, {NumBlocks: 1, DataCodewords: 17}}},
	},
	35: {
		ecc.L: {ECCodewordsPerBlock: 30, Groups: []BlockGroup{{NumBlocks: 12, DataCodewords: 121}, {NumBlocks: 7, DataCodewords: 122}}},
		ecc.M: {ECCodewordsPerBlock: 28, Groups: []BlockGroup{{NumBlocks: 12, DataCodewords: 47}, {NumBlocks: 26, DataCodewords: 48}}},
		ecc.Q: {ECCodewordsPerBlock: 30, Groups: []BlockGroup{{NumBlocks: 39, DataCodewords: 24}, {NumBlocks: 14, DataCodewords: 25}}},
		ecc.H: {ECCodewordsPerBlock: 30, Groups: []BlockGroup{{NumBlocks: 22, DataCodewords: 15}, {NumBlocks: 41, DataCodewords: 16}}},
	},
	36: {
		ecc.L: {ECCodewordsPerBlock: 30, Groups: []BlockGroup{{NumBlocks: 6, DataCodewords: 121}, {NumBlocks: 14, DataCodewords: 122}}},
		ecc.M: {ECCodewordsPerBlock: 28, Groups: []BlockGroup{{NumBlocks: 6, DataCodewords: 47}, {NumBlocks: 34, DataCodewords: 48}}},
		ecc.Q: {ECCodewordsPerBlock: 30, Groups: []BlockGroup{{NumBlocks: 46, DataCodewords: 24}, {NumBlocks: 10, DataCodewords: 25}}},
		ecc.H: {ECCodewordsPerBlock: 30, Groups: []BlockGroup{{NumBlocks: 2, DataCodewords: 15}, {NumBlocks: 64, DataCodewords: 16}}},
	},
	37: {
		ecc.L: {ECCodewordsPerBlock: 30, Groups: []BlockGroup{{NumBlocks: 17, DataCodewords: 122}, {NumBlocks: 4, DataCodewords: 123}}},
		ecc.M: {ECCodewordsPerBlock: 28, Groups: []BlockGroup{{NumBlocks: 29, DataCodewords: 46}, {NumBlocks: 14, DataCodewords: 47}}},
		ecc.Q: {ECCodewordsPerBlock: 30, Groups: []BlockGroup{{NumBlocks: 49, DataCodewords: 24}, {NumBlocks: 10, DataCodewords: 25}}},
		ecc.H: {ECCodewordsPerBlock: 30, Groups: []BlockGroup{{NumBlocks: 24, DataCodewords: 15}, {NumBlocks: 46, DataCodewords: 16}}},
	},
	38: {
		ecc.L: {ECCodewordsPerBlock: 30, Groups: []BlockGroup{{NumBlocks: 4, DataCodewords: 122}, {NumBlocks: 18, DataCodewords: 123}}},
		ecc.M: {ECCodewordsPerBlock: 28, Groups: []BlockGroup{{NumBlocks: 13, DataCodewords: 46}, {NumBlocks: 32, DataCodewords: 47}}},
		ecc.Q: {ECCodewordsPerBlock: 30, Groups: []BlockGroup{{NumBlocks: 48, DataCodewords: 24}, {NumBlocks: 14, DataCodewords: 25}}},
		ecc.H: {ECCodewordsPerBlock: 30, Groups: []BlockGroup{{NumBlocks: 42, DataCodewords: 15}, {NumBlocks: 32, DataCodewords: 16}}},
	},
	39: {
		ecc.L: {ECCodewordsPerBlock: 30, Groups: []BlockGroup{{NumBlocks: 20, DataCodewords: 117}, {NumBlocks: 4, DataCodewords: 118}}},
		ecc.M: {ECCodewordsPerBlock: 28, Groups: []BlockGroup{{NumBlocks: 40, DataCodewords: 47}, {NumBlocks: 7, DataCodewords: 48}}},
		ecc.Q: {ECCodewordsPerBlock: 30, Groups: []BlockGroup{{NumBlocks: 43, DataCodewords: 24}, {NumBlocks: 22, DataCodewords: 25}}},
		ecc.H: {ECCodewordsPerBlock: 30, Groups: []BlockGroup{{NumBlocks: 10, DataCodewords: 15}, {NumBlocks: 67, DataCodewords: 16}}},
	},
	40: {
		ecc.L: {ECCodewordsPerBlock: 30, Groups: []BlockGroup{{NumBlocks: 19, DataCodewords: 118}, {NumBlocks: 6, DataCodewords: 119}}},
		ecc.M: {ECCodewordsPerBlock: 28, Groups: []BlockGroup{{NumBlocks: 18, DataCodewords: 47}, {NumBlocks: 31, DataCodewords: 48}}},
		ecc.Q: {ECCodewordsPerBlock: 30, Groups: []BlockGroup{{NumBlocks: 34, DataCodewords: 24}, {NumBlocks: 34, DataCodewords: 25}}},
		ecc.H: {ECCodewordsPerBlock: 30, Groups: []BlockGroup{{NumBlocks: 20, DataCodewords: 15}, {NumBlocks: 61, DataCodewords: 16}}},
	},
}
